Repository MiaYWei/Group_G_UNO-Card-Game, pull requests merged in 2020-12, with the labels that each got.

#38 Game rules display updated
  src/menu_display.c
Labels: enhancement

#39 Draw card fix for human and code cleanup
  src/cards_management.c
  src/cards_management.h
  src/game.c
  src/human_player_module.c
  src/menu_display.c
Labels: bug, documentation

#41 Sys bug fix and code cleanup
  src/cards_management.c
  src/cards_management.h
  src/game.c
  src/game.h
  src/human_player_module.c
Labels: bug

#42 Update cards_management.c
  src/cards_management.c
Labels: enhancement

#43 Added shuffle cards in initialize_cards(void) & fixed compile warnings
  src/cards_management.c
  src/cards_management.h
  src/menu_display.c
  src/return_types.h
Labels: bug, enhancement

#44 Added new validation for human turn and cleaned up code
  src/cards_management.c
  src/game.c
  src/human_player_module.c
  src/human_player_module.h
Labels: bug, enhancement

#45 Release1 changes
  src/human_player_module.c
  src/menu_display.c
Labels: bug

#47 Add makefile for compiling project
  bin/Group_G_UNO-Card-Game.exe
  exe/Group_G_UNO-Card-Game_v0.1.exe
  makefile
  src/game.c
  src/human_player_module.c
  src/menu_display.c
Labels: enhancement

#49 Fixed main menu display issues.
  src/menu_display.c
Labels: bug

#50 Added player name inquiry when start a new game.
  src/game.c
  src/game.h
  src/menu_display.c
Labels: enhancement

#51 Merge Release v1.0 from development to master branch
  Group_G_UNO-Card-Game v1.0.exe
  bin/Group_G_UNO-Card-Game.exe
  doc/UNO_Express_Flowchart - Release 1.png
  makefile
  obj/cards_management.o
  obj/game.o
  obj/human_player_module.o
  obj/menu_display.o
  src/cards_management.c
  src/cards_management.h
  src/game.c
  src/game.h
  src/human_player_module.c
  src/human_player_module.h
  src/menu_display.c
  src/return_types.h
  test/src/test_cards_management.c
  test/src/test_human_player_module.c
Labels: enhancement

#53 Bug fix
  src/cards_management.c
  src/game.c
  src/human_player_module.c
  src/menu_display.c
Labels: bug

#54 Unit Test Update
  include/cards_management.h
  include/game.h
  include/human_player_module.h
  include/return_types.h
  src/cards_management.c
  src/game.c
  src/human_player_module.c
  src/menu_display.c
  test/include/test.h
  test/include/test_cards_management.h
  test/include/test_game.h
  test/src/test.c
  test/src/test_cards_management.c
  test/src/test_game.c
  test/src/test_human_player.c
Labels: enhancement

#55 Updated Unit test Cases - game and cards management module
  include/cards_management.h
  src/cards_management.c
  src/game.c
  test/include/test.h
  test/include/test_human_player.h
  test/src/test.c
  test/src/test_cards_management.c
  test/src/test_game.c
  test/src/test_human_player.c
Labels: enhancement

#36 Computer
  include/cards_management.h
  include/computer_player.h
  src/cards_management.c
  src/computer_player.c
  src/game.c
  src/human_player_module.c
Labels: enhancement

#58 Makefile compile test
  bin/Group_G_UNO-Card-Game.exe
  include/computer_player.h
  include/human_player.h
  makefile
  src/computer_player.c
  src/game.c
  src/human_player.c
  test/src/test_human_player.c
Labels: enhancement

#59 Skip Card
  include/cards_management.h
  include/game.h
  include/human_player.h
  include/return_types.h
  src/cards_management.c
  src/game.c
  src/human_player.c
  test/src/test_cards_management.c
Labels: enhancement

#60 Draw One Card - Human Player
  include/cards_management.h
  include/game.h
  include/human_player.h
  src/cards_management.c
  src/computer_player.c
  src/game.c
  src/human_player.c
Labels: enhancement

#62 Updated Unit Test Cases: Game Module
  include/game.h
  include/human_player.h
  obj/human_player_module.o
  src/game.c
  src/human_player.c
  test/include/test_cards_management.h
  test/src/test_cards_management.c
  test/src/test_computer_player.c
  test/src/test_game.c
  test/src/test_human_player.c
Labels: unit test

#63 Unit Test: Human Player Module
  include/game.h
  include/human_player.h
  include/return_types.h
  src/game.c
  src/human_player.c
  test/src/test_game.c
  test/src/test_human_player.c
Labels: unit test

#66 Makefile Update: relocate all test object files to obj folder, instead of test/obj
  makefile
Labels: improvement

#68 If statement cleanup
  src/cards_management.c
  src/game.c
  src/human_player.c
  src/menu_display.c
Labels: improvement

#64 Computer action
  include/computer_player.h
  src/cards_management.c
  src/computer_player.c
  src/game.c
Labels: enhancement

#67 Relocate test log & Add unplayable card warning
  include/human_player.h
  src/cards_management.c
  src/computer_player.c
  src/game.c
  src/human_player.c
  src/menu_display.c
  test/src/test.c
Labels: improvement

#69 Computer cleanup
  include/cards_management.h
  include/computer_player.h
  include/game.h
  include/human_player.h
  include/return_types.h
  src/cards_management.c
  src/computer_player.c
  src/game.c
  src/human_player.c
  src/menu_display.c
  test/include/test.h
  test/include/test_cards_management.h
  test/include/test_computer_player.h
  test/include/test_game.h
  test/include/test_human_player.h
  test/src/test_computer_player.c
Labels: improvement

#70 Added test/data folder
  test/data/test_log.txt
Labels: enhancement

#65 Readme update
  README.md
Labels: documentation

#71 Create LICENSE
  LICENSE
Labels: documentation

#72 Updated cards init - ensure the first card on table is a normal card.
  include/cards_management.h
  include/game.h
  include/human_player.h
  src/cards_management.c
  src/game.c
  src/human_player.c
  test/src/test_cards_management.c
  test/src/test_computer_player.c
  test/src/test_human_player.c
Labels: improvement

#78 Adding gitIgnore file
  .gitignore
  obj/cards_management.o
  obj/game.o
  obj/menu_display.o
  userManual.md
Labels: enhancement

#74 Update makefile
  makefile
Labels: bug

#80 Wild card bug
  include/cards_management.h
  include/console_print.h
  include/human_player.h
  src/console_print.c
  src/game.c
  src/human_player.c
  src/menu_display.c
Labels: bug, improvement

#82 fixed the test application compile issue: added console_print.c.
  makefile
  src/computer_player.c
  src/human_player.c
Labels: bug

#83 Fixed issues & Updated winner print on green color
  include/computer_player.h
  include/console_print.h
  src/cards_management.c
  src/computer_player.c
  src/console_print.c
  src/game.c
  src/human_player.c
Labels: bug, improvement

#84 Fixed test cases and code cleanup
  include/cards_management.h
  src/human_player.c
  test/include/test_human_player.h
  test/src/test.c
  test/src/test_human_player.c
Labels: bug, documentation

#85 Cleanup
  doc/UNO_Express_Flowchart - Release 1.png
  include/cards_management.h
  src/cards_management.c
  src/computer_player.c
  src/game.c
  src/human_player.c
  src/menu_display.c
  test/src/test.c
Labels: bug, improvement

#81 Add computer unit test with newest code
  include/computer_player.h
  test/src/test_computer_player.c
Labels: unit test

#86 Modifying user input and code cleanup
  .gitignore
  README.md
  src/cards_management.c
  src/computer_player.c
  src/game.c
  src/menu_display.c
  test/data/test_log.txt
  userManual.md
Labels: bug, documentation

#87 Adding folder
  .gitignore
  bin/UNO-Card-Game.exe
  bin/UNO-Card-Game_Test.exe
  obj/cards_management.o
  obj/computer_player.o
  obj/console_print.o
  obj/game.o
  obj/human_player.o
  obj/menu_display.o
  obj/test.o
  obj/test_cards_management.o
  obj/test_computer_player.o
  obj/test_game.o
  obj/test_human_player.o
  src/cards_management.c
  test/data/test_log.txt
Labels: documentation, improvement

#88 Makefile update and cleanup
  README.md
  include/cards_management.h
  include/computer_player.h
  makefile
  src/cards_management.c
  src/computer_player.c
  src/game.c
  src/human_player.c
Labels: bug, documentation, enhancement

#89 Reshuffling Issue
  include/cards_management.h
  src/cards_management.c
  src/computer_player.c
  src/game.c
  src/human_player.c
  test/src/test_computer_player.c
Labels: bug

#90 Fix issue and added related unit test
  src/computer_player.c
  test/src/test_computer_player.c
Labels: bug

#93 Doxy files
  README.md
  doc/Doxyfile_config
  doc/UNO_Express_Flowchart.png
  makefile
Labels: enhancement
